development:
  adapter: postgresql
  database: collection_dev
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  adapter: postgresql
  database: collection_test
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: password

  # sudo /etc/init.d/postgresql restart
